---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: PacketMachineTemplate
metadata:
  name: {{ .Values.clusterName }}-control-plane
spec:
  template:
    spec:
      billingCycle: hourly
      machineType: {{ .Values.controlPlane.machineType }}
      os: {{ .Values.controlPlane.os }}
      sshKeys: {{ .Values.sshKeys }}